### ISSUE TITLE
Create Production Build

### ISSUE THREAD

**Issue by nilsjung** [karsil/MobileReceptionAtlas#41]
* Create Production Build with Expo for Android (if possible for ios)

**Comment by karsil** [comment]
https://docs.expo.io/versions/latest/distribution/building-standalone-apps/

**Comment by karsil** [comment]
1. For Android `expo build:android`
2. Login as User
3. Let Expo handle it
4. Download APK after Expo build App

**Comment by karsil** [comment]
Todo:
> Must specify a java package in order to build this experience for Android. Please specify one in app.json at "expo.android.package"

**Comment by karsil** [comment]
https://stackoverflow.com/questions/50884026/is-google-maps-api-key-necessary-for-practice?rq=1
